# Generated by Django 4.1.7 on 2023-09-02 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='Booking_date',
            new_name='booking_date',
        ),
    ]
